--- 
title: "Beach Morphology Characteristics of Sea Turtle Nesting Sites: A Statistical Analysis"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# {-}

<center>

By: Jordan Iserman

Advisor: Dr. Samantha Seals


<br>


An Undergraduate Proseminar

In Partial Fulfillment of the Degree of

Bachelor of Science in Mathematics 

The University of West Florida

May 2022

</center>

# Approval Page {-}

The Proseminar of Jordan Iserman is approved:





________________________________________________   __________

Samantha Seals, Ph.D., Proseminar Advisor                   Date



________________________________________________   __________

Josaphat Uvah, Ph.D., Proseminar Committee Chair             Date





Accepted for the Department:



________________________________________________   __________

Jia Liu, Ph.D., Department Chair                           Date

# Abstract {-}

The population of sea turtles has been decreasing over the last 30 years. This is a problem because the extinction of one species can cause ripple effects throughout the entire biosphere. The purpose of this report is to determine if there are statistically significant differences in beach characteristics between the nest line and the locations near the nest line in loggerhead and green turtles. Foreshore slope, beach slope, beach width, and foredune height were measured at the nest profile line and 25, 50, and 100 meters both east and west of the nest line. Paired t-tests and Wilcoxon signed-rank tests were performed to compare both the nest line to the other locations and the east to the west locations of the same distance from the nest line. 90% confidence intervals for the mean and median differences were constructed. Statistical significance was defined as $\alpha = 0.1$

# Table of Contents {-}


Approval Page . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . i
<br>
Abstract . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ii
<br>
Table of Contents . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . iii
<br>
Introduction . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1
<br>
 Statement of Problem . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .1.1
<br>
 Relevance of Problem. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1.2
<br>
 Literature Review . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1.3
<br>
Methods . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
<br>
 Data . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.1
<br>
 Variables. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.1.1
<br>
 Statistical Methods . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.2
<br>
  Paired t-test. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.2.1
<br>
  Wilcoxon Signed-rank test. . . . . . . . . . . . . . . . . . . . . . . . . . . 2.2.2
<br>
  Confidence Intervals . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.2.3
<br>
 Analysis of the Current Data . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.3
<br>
 Analysis Results . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.4
<br>
  Foreshore Slope. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.4.1
<br>
  Beach Slope. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.4.2
<br>
  Beach Width. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.4.3
<br>
  Foredune Height. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.4.4
<br>
Conclusions. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3
<br>
 Summary:Interpretation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3.1
<br>
 Limitations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3.2
<br>
References. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . iv
<br>
Appendix. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . v

# Introduction

## Statement of Problem

As the population of sea turtles decreases, extinction becomes more of a possibility in the future. The loss of these turtles could threaten the overall biodiversity of the world. If the turtles go extinct, other species that rely on the turtles as food may experience a decrease in population. Other species that exist as food for the turtles will lose a predator and may experience an increase in population. The availability of nest sites for turtles has been declining, which is largely due to human activities, such as development in coastal areas and sea level rise as a result of climate change. The reduction of nest sites will result in less turtles nesting, which would lead to a further reduction of the population. This study examines beach morphological characteristics at and around the nest line to determine which variables are important to nest site selection.

## Relevance of Problem

Biodiversity is important because the loss of one species can have effects on multiple other species. One species may prey on another, while being prey for different species. If one species loses one of their major predators, their numbers can grow much higher. If a species loses a source of food, it is likely that there will be a reduction in the population of that species. A population change of one species will affect the populations of other species, and a chain reaction will occur. Humans may be involved as a link in this chain.

## Literature Review

There have been multiple studies that have attempted to model sea turtle nest site selection. A beach at El Cuyo, Mexico was examined to see if beach morphological characteristics influence probability of a site being used for nesting. Many variables affect nest-site selection, such as beach slope, orientation, width, oceanographic conditions, grain size, humidity, pH, temperature, and sand compression. They used Spearman correlation analyses between the number of nests in an area and the primary morphological characteristics. The total mean slope and the mean dune slope were able to explain 85.4% of the variability in beach profile. The correlation between total mean slope and berm slope was the only statistically significant (*p* < 0.05) correlation. Green turtle nest selection was negatively correlated with the berm slope (*r* = -0.67). Spearman correlation analyses were constructed to examine the effect of the beach slope and width on nest site selection. [1]

Culver et al. attempted to model the probability of a nest being in a location using beach geomorphology characteristics. This study focuses on Kemp’s Ridley turtles. Generalized linear models were constructed to model nest site selection using elevation, distance from shoreline, maximum dune slope, and average beach slope. Elevation and distance from shoreline were the most influential variables in the models. Each variable was significant in every linear model (*p* < 0.001), and explained 40-46% of the variability. [2]

A study done by Mortimer, J. was done to test if grain size of sand has an impact on nest site mortality, and to study nesting behaviors of sea turtles. Larger mean particle size is correlated with higher mortality. The number of trial nest holes and the mean particle diameter of sand were positively correlated using Spearman correlation (*r* = 0.815; *p* = 0.0001; *n* = 20). This study looked at green turtle nests and found that courser sands require more physiological effort for turtles to dig through. [3]

A study by Provancha, J. and Ehrhart, L. looked at correlations between total emergences and beach morphological characteristics. Beach slope and total emergences were positively correlated (*r* = 0.86). It is stated that beach slope is correlated to multiple off-shore factors as well, so it is possible that turtles are using the off-shore characteristics to help them select a nesting site. [4]

The goal of this study by Zavaleta-Lizarraga, L. and Morales-Mavil, J. was to determine the nesting variations of the green turtle. They tested the number of nests in different months of the year from June to September. Most of the nests were recorded in July and the least were recorded in September. There were not statistically significant differences between years, but there were between months (F = 4.45, p < 0.05). Certain beaches showed higher nesting probabilities (F = 14.07, p <0.01). Certain areas contained more nests. For example, the dune zone included 1206 nests, while the sandy beach zone contained 419 nests, and the tidal zone only contained 29. ANOVA was used for comparison in this study. [5]
